# Utiliser une image Python officielle
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app.py .


# Commande de démarrage
CMD ["python", "app.py"]
