# on build depuis une image 22 alpine 
FROM node:22-alpine AS builder

# definir la variable environnement et limiter les logs aux warnings
ENV NODE_ENV=production CI=true NPM_CONFIG_LOGLEVEL=warn

# definir le repertoire de travail
WORKDIR /app

# copier les fichiers de package.json (dépendances en cache)
COPY package*.json ./

# dépendances en mode production sans les devDependencies
RUN npm ci --omit=dev --no-audit --no-fund
#copier le reste des fichiers de notre appli
COPY node_modules ./node_modules
COPY . /app

#build
RUN npm run build




# implementation runner
FROM node:22-alpine AS runner

# environnement en mode production
ENV NODE_ENV=production
# redefinition repertoire de travail
WORKDIR /app


# avec un utilisateur non root (safety)
RUN addgroup -S appgrp && adduser -S app -G appgrp

# copier les fichiers necessaires
COPY --from=builder /app/. /app

#on expose le port 5000
EXPOSE 5000

#on lance notre application avec un utilisateur non root
USER app

# commande de lancement
CMD ["node", "server.js"]